pages:
  - name: Introduction
    # isPlaceholder: true => this would be non-clickable
    file: Introduction.md
    childs:
      - name: Get Started
        file: MarkedDocsCopy.md
      - name: Authentication
        file: Test2.md
      - name: Scaling
        file: Get_Started.md
  - name: Analytics
    file: Introduction.md
  - name: Database
    file: Introduction.md
    childs:
      - name: Endpoints
        file: Introduction.md
      - name: Structure
        file: Introduction.md